### ISSUE TITLE
Tag Rules are not working for headers (both standard and custom)

### ISSUE THREAD

**Issue by spiros-p** [curiefense/curiefense#353] opened 2021-05-17 02:00 UTC
**Tag Rules based on header values are not working**

Tag Rules are working for some http parameters (e.g., method and path), but are not working consistently for headers. 

This is true for both standard http headers (e.g., `user-agent`) and custom headers (e.g., `foo`).

**To Reproduce**
1. I created a tag rule to attach a tag of `demo-success` when a request matches any of these headers:
 
   -- `foo: bar`
    -- `x-forwarded-proto: http` or `http$`
    -- `user-agent: curl`

<img width="1108" alt="Screen Shot 2021-05-16 at 6 05 10 PM" src="https://user-images.githubusercontent.com/50348585/118422019-331f8800-b677-11eb-8e53-b16557711b48.png">

2. To verify that tag rules were propagating correctly and operational, I also created separate rules to:

    -- tag with `get-method` for method `GET`
    -- tag with `api-endpoint` for path `/api\/my-endpoint`

<img width="1113" alt="Screen Shot 2021-05-16 at 6 04 11 PM" src="https://user-images.githubusercontent.com/50348585/118422015-30bd2e00-b677-11eb-8033-0c14b9173f1c.png">
<img width="1108" alt="Screen Shot 2021-05-16 at 6 04 35 PM" src="https://user-images.githubusercontent.com/50348585/118422018-31ee5b00-b677-11eb-975c-7a2122d355d2.png">
 
3. I then sent this command:

`curl http://<redacted>/api/my-endpoint -H "foo: bar"`

**Expected behavior**
Along with its standard tags, this request should be tagged with `demo-success`, `get-method`, and `api-endpoint`.

As shown in the screenshot, the tags `get-method` and `api-endpoint` were attached, but `demo-success` was not.

<img width="1839" alt="Screen Shot 2021-05-16 at 6 06 09 PM" src="https://user-images.githubusercontent.com/50348585/118422021-33b81e80-b677-11eb-88c3-3ba8d6055008.png">

**Screenshots**

The Access Log screenshot shows that the headers themselves are being parsed correctly.  

(Also, the additional tag of `api` can be ignored -- this is from a leftover API Discovery tag rule built for a previous test.)

**Additional context**
These tagging problems are present even when working with rules with only one match criterion. In other words, if you break up the  three-header tag rule described above into three separate rules, this does not solve the problem.

**Comment by spiros-reblaze** [comment] 2021-05-18 07:00
**More information**

My Curiefense instance periodically gets wiped and rebuilt, so that I have the latest version. However, this also wipes whatever configuration has been done since the last rebuild, and the instance reverts to an older configuration.

The older configuration includes a Tag Rule that will attach a tag to a request with a header of `foo: bar`. 

<img width="1066" alt="Screen Shot 2021-05-17 at 11 25 57 PM" src="https://user-images.githubusercontent.com/50348585/118602702-dcde4200-b767-11eb-9172-a5c6643b6afe.png">

**This tag rule works.** However, when I create an identical tag rule from scratch, the new one does *not* work.

(I thought this might be explained by a conflict between two identical rules, but the new one will not work regardless of whether the older one is set to Active or not.)

**Speculation**

Perhaps a bug was introduced into Curiefense so that it's not correctly storing new Tag Rule criteria if they are based on header values, and the old rule was created before this happened (and thus, was stored correctly).

If so, the problem was introduced sometime after, or simultaneously with, the UI update that changed its default name for new rules (from "New Profiling List" to "New Tag Rule").

I also noticed that within the UI, the older rule shows an unidentified string (`baz`), while new header rules do not have a field here.

Currently for headers, the UI does not ask for annotations; I don't remember if this has always been the case. Perhaps this is related to the above.

**Comment by bartavelle** [comment] 2021-06-17 09:45
This *should* work with the rust code, if that is not a configuration propagation issue. One thing that would be extremely helpful would be to download the configuration JSON (which I believe you can do from the UI), and attach it here.

I will try to reproduce this on my own VM.

**Comment by bartavelle** [comment] 2021-06-17 12:04
It does "work for me", with the Rust code. Let's test this again when it is merged!

**Comment by bartavelle** [comment] 2021-07-13 15:45
Is that ok now?

**Comment by Aviv-Galmidi** [comment] 2021-07-22 09:53
I can confirm that it is still an issue. I've tested a Tag Rule with the following settings.
However, when I sent a request with `PUT` method the tags were added, and when I sent a request with header `foo:bar` they were not

```
{
  "mdate": "2021-07-22T09:39:09.512Z", 
  "name": "A - Testing ACL - All tags", 
  "tags": [
    "enforce_deny", 
    "bypass", 
    "allow_bot", 
    "deny_bot", 
    "allow", 
    "deny"
  ], 
  "notes": "New List Notes and Remarks", 
  "rule": {
    "relation": "OR", 
    "sections": [
      {
        "relation": "OR", 
        "entries": [
          [
            "method", 
            "PUT", 
            ""
          ]
        ]
      }, 
      {
        "relation": "OR", 
        "entries": [
          [
            "headers", 
            [
              "foo", 
              "bar"
            ]
          ]
        ]
      }
    ]
  }, 
  "source": "self-managed", 
  "action": {
    "type": "monitor"
  }, 
  "active": true, 
  "id": "5b3ff696cb1d"
}
```

**Comment by bartavelle** [comment] 2021-07-22 10:17
I can't reproduce it :( Can you put envoy in debug mode, and paste the whole log to me? I use this command to retrieve the relevant data:

```shell
docker-compose logs -f curieproxy | sed -e 's/^.*script log: /LOG: /' | grep 'LOG: '
```

**Comment by Aviv-Galmidi** [comment] 2021-07-22 11:50
I might have done something wrong, but when running hte provided command I get this

```
LOG: ACL Check -- Request details 
LOG: ACL Check Bot -- Request details 
LOG: ACL Check -- Request details 
LOG: ACL Check Bot -- Request details 
```

More detailed log when I'm searching for `script log: ` in the cuireproxy logs
```
curieproxy       | [2021-07-22 11:45:29.241][19][debug][conn_handler] [source/server/connection_handler_impl.cc:542] [C4] new connection
curieproxy       | [2021-07-22 11:45:29.244][19][debug][http] [source/common/http/conn_manager_impl.cc:254] [C4] new stream
curieproxy       | [2021-07-22 11:45:29.244][19][debug][http] [source/common/http/conn_manager_impl.cc:879] [C4][S15022497662479594495] request headers complete (end_stream=true):
curieproxy       | ':authority', 'localhost:30081'
curieproxy       | ':path', '/'
curieproxy       | ':method', 'GET'
curieproxy       | 'user-agent', 'curl/7.64.1'
curieproxy       | 'accept', '*/*'
curieproxy       | 'foo', 'bar'
curieproxy       | 
curieproxy       | [2021-07-22 11:45:29.245][19][debug][http] [source/common/http/filter_manager.cc:773] [C4][S15022497662479594495] request end stream
curieproxy       | [2021-07-22 11:45:29.251][19][debug][lua] [source/extensions/filters/http/lua/lua_filter.cc:757] script log: ACL Check -- Request details 
curieproxy       | {"query":"","tags":{"wafname:default-waf":1,"urlmap:default-entry":1,"container:curieproxy":1,"benforcedeny":1,"bbypass":1,"ballowbot":1,"bdenybot":1,"ballow":1,"bdeny":1,"trusted":1,"urlmap-entry:default":1,"aclname:default-acl":1,"ip:172-22-0-1":1,"curieaccesslog":1,"all":1,"geo:nil":1,"asn:nil":1,"aclid:--default--":1,"wafid:--default--":1},"xff_trusted_hops":1,"method":"GET","authority":"localhost:30081","path":"\/","remote_addr":"172.22.0.1","ipnum":2887122945,"scheme":"http","uri":"\/","ip":"172.22.0.1"}
curieproxy       | 
curieproxy       | [2021-07-22 11:45:29.251][19][debug][lua] [source/extensions/filters/http/lua/lua_filter.cc:757] script log: ACL Check Bot -- Request details 
curieproxy       | {"query":"","tags":{"wafname:default-waf":1,"urlmap:default-entry":1,"container:curieproxy":1,"benforcedeny":1,"bbypass":1,"ballowbot":1,"bdenybot":1,"ballow":1,"bdeny":1,"trusted":1,"urlmap-entry:default":1,"aclname:default-acl":1,"ip:172-22-0-1":1,"curieaccesslog":1,"all":1,"geo:nil":1,"asn:nil":1,"aclid:--default--":1,"wafid:--default--":1},"xff_trusted_hops":1,"method":"GET","authority":"localhost:30081","path":"\/","remote_addr":"172.22.0.1","ipnum":2887122945,"scheme":"http","uri":"\/","ip":"172.22.0.1"}
curieproxy       | 
curieproxy       | [2021-07-22 11:45:29.252][19][debug][lua] [source/extensions/filters/common/lua/lua.cc:39] coroutine finished
curieproxy       | [2021-07-22 11:45:29.252][19][debug][router] [source/common/router/router.cc:445] [C4][S15022497662479594495] cluster 'target_site' match for URL '/'
curieproxy       | [2021-07-22 11:45:29.253][19][debug][router] [source/common/router/router.cc:628] [C4][S15022497662479594495] router decoding headers:
curieproxy       | ':authority', 'localhost:30081'
curieproxy       | ':path', '/'
curieproxy       | ':method', 'GET'
curieproxy       | ':scheme', 'http'
curieproxy       | 'user-agent', 'curl/7.64.1'
curieproxy       | 'accept', '*/*'
curieproxy       | 'foo', 'bar'
curieproxy       | 'x-forwarded-for', '172.22.0.1'
curieproxy       | 'x-forwarded-proto', 'http'
curieproxy       | 'x-envoy-internal', 'true'
curieproxy       | 'x-request-id', 'bb2d8454-f590-4fe0-b7b4-53de2c2f1503'
curieproxy       | 'x-envoy-expected-rq-timeout-ms', '15000'
```

**Comment by bartavelle** [comment] 2021-07-22 11:57
Did you edit the environment file to set envoy log levels to debug?

**Comment by bartavelle** [comment] 2021-07-22 12:00
It seems like you are running a very old version, it is still the Lua code!

https://github.com/curiefense/curiefense/blob/3bd8a98d8288fc26b4433aecde09c06398808bc8/curiefense/curieproxy/lua/acl.lua#L56

**Comment by Aviv-Galmidi** [comment] 2021-07-22 12:14
hmm... I pulled the latest main and ran `docker-compose up` after making sure I don't have any images `docker-compose images`. I'm not sure why it used an old image for the curieproxy but gave me the new version of ui (1.3.8)

I'm trying to prune the images again and re-installing the env from scratch. I'll update soon

**Comment by Aviv-Galmidi** [comment] 2021-07-22 12:30
I probably missed a curieproxy image in `docker images` and pruned some curiefense images but not all of them, which caused my weird half-updated scenario
I pruned me entire image db from the machine - and installed everything from scratch (hopefully, assuming no more kinks this time)
Running with the latest version, I can't reproduce this bug. Tag Rules with headers assign the correct tags and are working properly. I also do not get the `ACL Check Bot` log anymore which hopefully mean I'm actually running the latest version now

**Comment by Aviv-Galmidi** [comment] 2021-07-28 09:11
Closing as cannot reproduce with the latest version

**Closed by Aviv-Galmidi** 2021-07-28 09:11 UTC
Labels: bug
