### ISSUE TITLE
Tags - after deleting lists and not using the tags in ACL anymore we still present the tags 

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#429] opened 2021-07-11 08:45 UTC
**Describe the bug**
After deleting the tag rules lists with vpn and tor tags and the tags from ACL we still present tags in requests 
**To Reproduce**
1. Go to Tag rules and create lists with vpn and tog tags 
2. add those tags into acl and verify that we add them into logs 
3. Delete all lists and tags from ACL 

**Expected behavior**
we should not get those tags in logs : 

tags | all, ip:172-18-0-1, asn:nil, urlmap-entry:default, container:curieproxy, aclname:default-acl, vpn, geo:nil, urlmap:default-entry, wafid:default-waf, aclid:--default--, tor, curieaccesslog
-- | --

**Comment by bartavelle** [comment] 2021-07-13 14:25
`vpn` and `tor` should be the tags that should be absent right?

**Comment by bartavelle** [comment] 2021-07-13 14:34
I could not reproduce it ...

**Comment by yanushg** [comment] 2021-07-13 19:37
Try with rate limit. Attach a rate limit to url map and send a request 
You will see the tag before it reaches the limit

**Comment by yanushg** [comment] 2021-07-14 05:34
For example: Rate limit is not triggered yes but we still tag with "testing-event" 
`{
  "_index": "curieaccesslog-2021.07.13-000011",
  "_type": "_doc",
  "_id": "KvCAo3oBsO6hXpSyzZ1b",
  "_version": 1,
  "_score": null,
  "_ignored": [
    "request.geo.location"
  ],
  "_source": {
    "@timestamp": "2021-07-14T05:32:30.701Z",
    "response": {
      "headersbytes": 123,
      "bodybytes": 267,
      "code": 200,
      "codedetails": "via_upstream"
    },
    "tags": [
      "geo:nil",
      "urlmap-entry:default",
      "wafid:--default--",
      "container:curieproxy",
      "aclname:default-acl",
      "testing-event",
      "wafname:default-waf",
      "all",
      "ip:172-20-0-1",
      "asn:nil",
      "urlmap:default-entry",
      "aclid:--default--",
      "curieaccesslog"
    ],
    "log": {
      "offset": 1929762,
      "file": {
        "path": "/var/lib/docker/containers/bb7e97c847c570b27b7f93c1968bc2e49c0fcafe91bbf55200832e1101099418/bb7e97c847c570b27b7f93c1968bc2e49c0fcafe91bbf55200832e1101099418-json.log"
      }
    },
    "metadata": {
      "invalidenvoyrequestheaders": false,
      "localreset": false,
      "noroutefound": false,
      "ratelimited": false,
      "nohealthyupstream": false,
      "routename": "",
      "samplerate": 0,
      "ratelimitserviceerror": false,
      "faultinjected": false,
      "streamidletimeout": false,
      "unauthorizeddetails": "REASON_UNSPECIFIED",
      "delayinjected": false,
      "failedlocalhealthcheck": false
    },
    "container": {
      "id": "bb7e97c847c570b27b7f93c1968bc2e49c0fcafe91bbf55200832e1101099418",
      "name": "curielogger",
      "image": {
        "name": "curiefense/curielogger:v1.3.0-262-g3966822-dirty-6079cbbbf901"
      }
    },
    "upstream": {
      "connectiontermination": false,
      "remotereset": false,
      "connectionfailure": false,
      "localaddressport": 58108,
      "requesttimeout": false,
      "remoteaddress": "172.20.0.4",
      "remoteaddressport": 8080,
      "localaddress": "172.20.0.10",
      "transportfailurereason": "",
      "retrylimitexceeded": false,
      "cluster": "target_site",
      "overflow": false
    },
    "blocked": false,
    "tx_timers": {
      "firstupstreambyte": "0.0036247000000000002",
      "lastupstreambyte": "0.0036475",
      "firstdownstreambyte": "0.0047329",
      "lastdownstreambyte": "0.0048421"
    },
    "downstream": {
      "localaddressport": 80,
      "protocolerror": false,
      "remoteaddress": "172.20.0.1",
      "remoteaddressport": 57896,
      "connectiontermination": false,
      "directremoteaddress": "172.20.0.1",
      "directremoteaddressport": 57896,
      "localaddress": "172.20.0.10"
    },
    "stream": "stdout",
    "tls": {
      "localcertificate": {
        "properties": "",
        "propertiesaltnames": []
      },
      "peercertificate": {
        "properties": "",
        "propertiesaltnames": []
      },
      "ciphersuite": "<nil>",
      "sessionid": "",
      "snihostname": "",
      "version": "VERSION_UNSPECIFIED"
    },
    "input": {
      "type": "container"
    },
    "docker": {
      "container": {
        "labels": {
          "com_docker_compose_oneoff": "False",
          "com_docker_compose_project_config_files": "docker-compose.yaml",
          "co_elastic_logs/enabled": "True",
          "co_elastic_logs/json_keys_under_root": "True",
          "com_docker_compose_config-hash": "230f62a16c6cdffdc823ac03d4000dc9a4e16af1f99f5805952d79ff83d9d61c",
          "com_docker_compose_version": "1.29.1",
          "com_docker_compose_project": "compose",
          "com_docker_compose_project_working_dir": "/Users/admin/Desktop/curielocal/curiefense/deploy/compose",
          "com_docker_compose_service": "curielogger",
          "co_elastic_logs/ignore_decoding_error": "True",
          "co_elastic_logs/json_add_error_key": "True",
          "com_docker_compose_container-number": "1"
        }
      }
    },
    "agent": {
      "ephemeral_id": "7c92d2e7-ed0b-4fcc-ad3d-9fd8ab825fdf",
      "id": "cc798b28-8ea1-46aa-8eb5-c8d8afebba99",
      "name": "73a0c4675da3",
      "type": "filebeat",
      "version": "7.10.1",
      "hostname": "73a0c4675da3"
    },
    "host": {
      "name": "73a0c4675da3"
    },
    "timestamp": "2021-07-14T05:32:30.257015Z",
    "request": {
      "attributes": {
        "ip": "172.20.0.1",
        "uri": "/test",
        "path": "/test",
        "method": "GET"
      },
      "requestid": "a529487e-c31b-4508-8246-c39986f6334a",
      "headersbytes": 235,
      "bodybytes": 0,
      "arguments": {},
      "cookies": {},
      "geo": {
        "city": {
          "name": "-"
        },
        "location": {},
        "country": {},
        "continent": {}
      },
      "scheme": "http",
      "headers": {
        "accept": "*/*",
        "x-request-id": "a529487e-c31b-4508-8246-c39986f6334a",
        "x-envoy-internal": "true",
        "x-forwarded-proto": "http",
        "x-forwarded-for": "172.20.0.1",
        "user-agent": "curl/7.64.1"
      }
    },
    "rx_timers": {
      "firstupstreambyte": "0.0046211",
      "lastupstreambyte": "0.0047968",
      "lastbyte": 0.00014780000000000001
    },
    "ecs": {
      "version": "1.6.0"
    }
  },
  "fields": {
    "@timestamp": [
      "2021-07-14T05:32:30.701Z"
    ],
    "timestamp": [
      "2021-07-14T05:32:30.257Z"
    ]
  },
  "sort": [
    1626240750701000000
  ]
}`

**Comment by bartavelle** [comment] 2021-07-15 06:23
I thought this was the correct design, so that you know a rate limit has been tested for a request. I think this is what the Lua code does?

**Comment by yanushg** [comment] 2021-07-18 07:25
No - we only tag when the rate limit is triggered - if we choose to do it this way - tag action makes no sense

**Comment by bartavelle** [comment] 2021-07-19 08:39
This automatically closed, I'll reopen it so that it can be confirmed to work.

**Comment by yanushg** [comment] 2021-07-19 12:14
Working as expected

**Comment by Aviv-Galmidi** [comment] 2021-07-22 10:18
Closing the issue as it has been confirmed to be working as expected

**Closed by Aviv-Galmidi** 2021-07-22 10:18 UTC
Labels: bug
