### ISSUE TITLE
The Kibana log does not displayed the correct  block_reason.name and block_reason.initiator when a request is blocked by challenge

### ISSUE THREAD

**Issue by semharel** [curiefense/curiefense#630] opened 2021-11-23 16:24 UTC
**Describe the bug**
Logs do not display the correct block_reason.name and block_reason.initiator when a request is blocked by challenge

**To Reproduce**
1. Go to 'Flow control'
2. Create a new object with a challenge action 
3.  Click on the create new section and  scroll to IP Address and put your IP 
4. save and send a request that appropriate to the global filter 
5.  Go to the kibana log 

**Expected behavior**
Usually the block_reason.name and block_reason.initiator give us the reason for creating the action / block
So we need to get  block_reason.name = a name of flow control that cause to challenge and block_reason.initiator = flow check 

**Screenshots**

![Screen Shot 2021-11-23 at 18 26 38](https://user-images.githubusercontent.com/86234718/143065201-70bf0a03-24a6-407a-b614-71a9c921677c.png)

![Screen Shot 2021-11-23 at 18 26 23](https://user-images.githubusercontent.com/86234718/143065250-522c934b-9dda-409e-b730-872636ae88ad.png)

**Comment by bartavelle** [comment] 2021-11-24 08:52
The only code path that can return this initiator, unless there is a bug, is when the URI starts with `/7060ac19f50208cbb6b45328ef94140a612ee92387e015594234077b4d1e64f1/` (the challenge response location). Isn't that the case here? In that case, it is not really possible to know it came from a flow control rule, as it is a distinct request, but you should have another request logged with the following reason:

```json
{
  "initiator": "flow_check",
  "name": "Flow Control (challenge)"
}
```

**Comment by flaper87** [comment] 2022-01-09 16:27
@semharel hey, hope @bartavelle answer helped here. This issue seems staled and I'm going to go ahead and close it for now. Feel free to re-open it if the issue is still valid.

**Closed by flaper87** 2022-01-09 16:27 UTC
Labels: bug
