### ISSUE TITLE
Where is the "Access Log" in https://docs.curiefense.io/installation/getting-started-with-curiefense

### ISSUE THREAD

**Issue by nathanawmk** [curiefense/curiefense#534] opened 2021-08-02 17:19 UTC
Where is the "Access Log" in https://docs.curiefense.io/installation/getting-started-with-curiefense? I am planning to demo this but I cannot see the Access Log.

I am from Singapore and I want to demo Curiefense so please help here

![image](https://user-images.githubusercontent.com/14244560/127899744-c0a8856f-2e19-4439-baba-61aa4c8738b2.png)

**Comment by jdorfman** [comment] 2021-08-04 16:13
Duplicate of #532

**Closed by jdorfman** 2021-08-04 16:13 UTC
Labels: question
