### ISSUE TITLE
Tag by Header is not working

### ISSUE THREAD

**Issue by yuvalbaryochay** [curiefense/curiefense#392] opened 2021-06-27 07:23 UTC
**Tag based on headers does not work**

**To Reproduce**
1. Go to 'TagRules' and set header `secret: kjsdhoiery8u3o`
2. Set ACL with Deny for all except for this tag
3. Send request `curl http://104.197.219.104:30081/admin -H "secret:kjsdhoiery8u3o"`
**Expected behavior**
request should NOT be blocked.

**Result**

```
➜  ~ curl http://104.197.219.104:30081/admin -H "secret:kjsdhoiery8u3o"
curiefense - request denied%
```

**Screenshots**
<img width="1149" alt="Screen Shot 2021-06-27 at 10 21 06" src="https://user-images.githubusercontent.com/86548537/123536193-83d3d780-d731-11eb-86b4-152ccf1134b8.png">
<img width="1095" alt="Screen Shot 2021-06-27 at 10 21 20" src="https://user-images.githubusercontent.com/86548537/123536197-859d9b00-d731-11eb-8dbb-ef33c6117472.png">
<img width="1038" alt="Screen Shot 2021-06-27 at 10 21 32" src="https://user-images.githubusercontent.com/86548537/123536199-86363180-d731-11eb-823d-1a5f6eff96a2.png">

**Comment by Aviv-Galmidi** [comment] 2021-06-28 15:09
Duplicate of https://github.com/curiefense/curiefense/issues/353

**Comment by flaper87** [comment] 2021-06-29 04:11
Closing based on https://github.com/curiefense/curiefense/issues/392#issuecomment-869767033

> @flaper87 do you have a preference on dups?

To close them :)

**Closed by flaper87** 2021-06-29 04:11 UTC
Labels: bug
